In [4]:
import numpy as np


In [5]:
def adjacency_matrix(edges, n):
    """creating adjacency matrix from a list of edges and number of nodes."""
    adj_matrix = np.zeros((n, n))
    for edge in edges:
        adj_matrix[edge[0], edge[1]] = 1
        adj_matrix[edge[1], edge[0]] = 1 
    return adj_matrix

def degree_matrix(adj_matrix):
    """returning degree matrix for the given adjacency matrix."""
    degrees = np.sum(adj_matrix, axis=1)
    return np.diag(degrees)

def laplacian_matrix(adj_matrix):
    """Calculate the Laplacian matrix from an adjacency matrix."""
    D = degree_matrix(adj_matrix)
    L = D - adj_matrix
    return L

In [8]:
edges = [(0, 1), (0, 2), (1, 2), (1, 3)]
n = 4
A = adjacency_matrix(edges, n)
L = laplacian_matrix(A)
D = degree_matrix(A)

print("Adjacency Matrix:\n", A)
print("Degree Matrix:\n", D)
print("Laplacian Matrix:\n", L)

Adjacency Matrix:
 [[0. 1. 1. 0.]
 [1. 0. 1. 1.]
 [1. 1. 0. 0.]
 [0. 1. 0. 0.]]
Degree Matrix:
 [[2. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 1.]]
Laplacian Matrix:
 [[ 2. -1. -1.  0.]
 [-1.  3. -1. -1.]
 [-1. -1.  2.  0.]
 [ 0. -1.  0.  1.]]


Adjacency Matrix: 
- for an adjacency matrix representing an undirected graph. The matrix is symmetric about the diagonal, meaning the upper triangular part of the matrix (above the diagonal) is a mirror reflection of the lower triangular part (below the diagonal). 

	•	Nodes 0 and 1 are adjacent (as indicated by the -1 at positions (0,1) and (1,0)).
	•	Nodes 0 and 2 are adjacent.
	•	Nodes 1 and 2 are adjacent.
	•	Nodes 1 and 3 are adjacent.

Degree Matrix:

	Node 0 has a degree of 2.
	•	Node 1 has a degree of 3.
	•	Node 2 has a degree of 2.
	•	Node 3 has a degree of 1.

Laplacian Matrix:

	•	Node 0 is connected to Nodes 1 and 2 (corresponding to -1 at (0,1) and (0,2)).
	•	Node 1 is connected to Nodes 0, 2, and 3 (corresponding to -1 at (1,0), (1,2), and (1,3)).
	•	Node 2 is connected to Nodes 0 and 1 (corresponding to -1 at (2,0) and (2,1)).
	•	Node 3 is connected only to Node 1 (corresponding to -1 at (3,1)).

- we just look at the Laplacian horizontally, for example at Row 0 (Node 0), we see -1 at position 1 and 2, therefore Node 0 is connected to Node 1 and Node 2

